apiVersion: v1
kind: Pod
metadata:
  name: gpu-nfs-access-test
  namespace: jhub
spec:
  containers:
  - name: tester
    image: ubuntu
    command: ["/bin/bash", "-c", "--"]
    args: ["apt update && apt install -y curl && while true; do sleep 30; done"]
    volumeMounts:
    - mountPath: /shared
      name: shared-vol
    securityContext{
      runAsUser = 1000
      fs_group  = 100
    }
  volumes:
  - name: shared-vol
    persistentVolumeClaim:
      claimName: shared-dataset-pvc
  restartPolicy: Never

