apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-dataset-pv
spec:
  capacity:
    storage: 98Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.162.87
    path: /mnt/nfs-share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-dataset
  namespace: jhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 98Gi
  volumeName: shared-dataset-pv

