apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
  namespace: jhub
spec:
  containers:
  - name: nfs-client
    image: ubuntu
    command: ["/bin/bash", "-c", "--"]
    args: ["apt update && apt install -y nfs-common && sleep 3600"]
    securityContext:
      privileged: true
  restartPolicy: Never

