apiVersion: v1
kind: Pod
metadata:
  name: gpu-job-manager
  namespace: jhub
  labels:
    app: gpu-job-manager
spec:
  restartPolicy: Always
  nodeSelector:
    accelerator: nvidia
  securityContext:
    runAsUser: 1000
    fsGroup: 100
  initContainers:
    - name: init-scripts
      image: busybox
      command:
        - /bin/sh
        - -c
        - mkdir -p /shared/scripts
      volumeMounts:
        - name: shared
          mountPath: /shared
  containers:
    - name: manager
      image: jupyter/scipy-notebook:latest
      command:
        - /bin/sh
        - -c
        - |
          pip install pyyaml kubernetes && \
          while true; do python /shared/scripts/gpu_job_manager.py; sleep 10; done
      volumeMounts:
        - name: shared
          mountPath: /shared
  volumes:
    - name: shared
      persistentVolumeClaim:
        claimName: shared-dataset-pvc

